let Plan = [
  {
    country: "Germany",
    countryCode: "de",
    places: [
      {
        id: Math.random(),
        name: "Nymphenburg palace",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Isar river and Zoo",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Marienplatz",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "English garten",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Ammersee",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Chiemsee",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Olmpia park and tower",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Bmw museum",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Deutsches museum",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "cuvilliés Theater",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Neuschwanstein castle",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Alpsee bergbelt",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Zugspitze",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Königssee",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Lake Constance",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "The Island of Rügen",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Austria",
    countryCode: "au",
    places: [
      {
        id: Math.random(),
        name: "Vienna - capital",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Salzburg",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Innsbruck",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Grossglockner Alpine Road",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Hallstat",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "5 fingers",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Tyrol – Heaven In The Alps",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Highline 179",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Switzerland",
    countryCode: "ch",
    places: [
      {
        id: Math.random(),
        name: "Interlaken",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Harderbahn – Interlaken evening/night",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Lucerne",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "The Rhine Falls",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Grindelwald",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Gelmerbahn Funicular",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Stoos Funicular",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Mt. Titlis – Engelberg",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Lauterbrunnen  waterfall",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Zwei seen steg",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Zurich",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Europa park",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Czech Republic",
    countryCode: "cz",
    places: [
      {
        id: Math.random(),
        name: "Prague",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Hungary",
    countryCode: "hu",
    places: [
      {
        id: Math.random(),
        name: "Hot spring bath",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Charles Bridge",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Ferry Ride",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Greece",
    countryCode: "gr",
    places: [
      {
        id: Math.random(),
        name: "Santorini",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Athens",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Ionian Islands",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Italy",
    countryCode: "it",
    places: [
      {
        id: Math.random(),
        name: "Rome",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Venice",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Florence",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Milan",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Vatican",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Leaning tower of Pisa",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Colosseum",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Lake Como",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Cinque Terre",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Naples",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "The Amalfi Coast",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "The Island of Capri",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Sardini",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "check saved insta videos",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Spain",
    countryCode: "es",
    places: [
      {
        id: Math.random(),
        name: "Barcelona",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Costa Brava",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Ibiza",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Mallorca Island",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "Croatia",
    countryCode: "hr",
    places: [
      {
        id: Math.random(),
        name: "Split",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Dubrovnik",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Zagreb - Capital",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Plitvice Lakes National Park",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Hvar",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
  {
    country: "France",
    countryCode: "fr",
    places: [
      {
        id: Math.random(),
        name: "Paris - Eiffel Tower",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
      {
        id: Math.random(),
        name: "Disney Land",
        visited: "no",
        gMapLink: "https://maps.google.com",
      },
    ],
  },
];
